sonar.projectKey=my-nestjs-project
sonar.projectName=NestJS Backend
sonar.projectVersion=1.0

# NestJS root source folder
sonar.sources=src

# Exclude compiled files, dependencies, and tests
sonar.exclusions=**/node_modules/**, dist/**, **/*.spec.ts, **/*.e2e-spec.ts, test/**

# Coverage report path (if you are running Jest tests beforehand)
sonar.javascript.lcov.reportPaths=coverage/lcov.info